/**
This file is generated by the build.js script in the cloud-wenwave-server.
Do not edit this file manually.
*/

resource "aws_lambda_function" "me" {
  function_name    = "${var.app_name}-me"
  filename         = "../server/dist/me.zip"
  source_code_hash = filebase64sha256("../server/dist/me.zip")
  handler          = "me.handler"
  runtime          = "nodejs18.x"
  role             = var.aws_iam_role_lambda_exec_arn
}

resource "aws_cloudwatch_log_group" "me_lambda_log_group" {
  name              = "/aws/lambda/${aws_lambda_function.me.function_name}"
  retention_in_days = 30

  depends_on = [aws_lambda_function.me]
}

output "me_lambda_arn" {
  value = aws_lambda_function.me.arn
}
